# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16YFnBbTEddbcShViAFxZqoyc2xPreVuo
"""

import numpy as np

a='ayush hendre'
k=a.split()
k

dir(a)

a=np.array([2,3,4])
a

type(a)

a.shape

a1=np.array([[1,2,3],[1,1,1]])
a1

a1.shape

a1.shape[1]

a1.sum(axis=1)

np.random.seed(1)

a2=np.random.rand(64,64,3)

a2

a2[:,:,2]

c=np.array([[2,3,4,5],[7,8,9,10]])
c.shape

d=c.T
d.shape

A=np.array([[2,3],[4,5]])
B=np.array([[1,2,3],[1,1,1]])
C=np.dot(A,B)
C.shape

A1=np.zeros((5,1))
print(A1)

c1=['a1','b1','d1']
type(c1)

c1.append('e1')
print(c1)

dir(c1)

e1={'a':11,'b':12}
type(e1)
e1.values()

##sigmoid
x=np.array([1,2,3])
x1=1/(1+np.exp(-x))
print(x1)

##derivatives of sigmoid
x1*(1-x1)

img=np.random.rand(2,2,3)

new_img=img.reshape((img.shape[0]*img.shape[1]*img.shape[2],1))
new_img.shape

print(new_img)

new_img1=img.reshape(img.shape[0],-1).T
new_img1.shape

x1=np.array([[0,3,4],[2,6,4]])
x1

x_norm=np.linalg.norm(x1,ord=2,axis=1,keepdims=True)
x_norm.shape
x_sd=x1/x_norm
x_sd

w,b,X,Y=np.array([[1],[2]]),2,np.array([[1,2,-1],[3,4,-3.2]]),np.array([[1,0,1]])

X.shape

print(X)





